import { exec, registerColumns } from './db';

/**
 * The PostgreSQL database of the web version, created on first start (every statement is idempotent).
 *
 * The first tables are the ones the Windows program's Entity Framework model has (src/ZkAttendance/Data), with the same
 * columns and the same seed rows (AppDbContext.Initialize): shift "General", department "General", leave types CL / SL /
 * EL / LWP and one device. The others were web-only already: PiCommands / PiDeviceUsers (Raspberry Pi bridge),
 * PortalAccounts / EmployeeRequests (employee portal and app) and the HR tables: EmployeeProfiles, EmployeeDocuments,
 * ShiftExtras (break timing), ShiftRoster (rotating shifts), SalaryComponents / EmployeeSalaryComponents (salary
 * structure), Notifications, AuditLog, AdminUsers (user roles) and WebBlobs (company logo).
 *
 * Names are unquoted (PostgreSQL keeps them in lower case); config/db gives result columns their PascalCase back.
 * SQL Server types: NVARCHAR → VARCHAR / TEXT, BIT → BOOLEAN, DATETIME2 → TIMESTAMP (local time), DECIMAL → NUMERIC.
 */
const SCHEMA = `
CREATE TABLE IF NOT EXISTS Departments (
  Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Name VARCHAR(100) NOT NULL,
  ParentId INT NULL
);
CREATE TABLE IF NOT EXISTS Shifts (
  Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Name VARCHAR(100) NOT NULL,
  StartTime TIME NOT NULL DEFAULT '09:00',
  EndTime TIME NOT NULL DEFAULT '18:00',
  LateGraceMinutes INT NOT NULL DEFAULT 10,
  EarlyGraceMinutes INT NOT NULL DEFAULT 10,
  HalfDayMinutes INT NOT NULL DEFAULT 240,
  MinOvertimeMinutes INT NOT NULL DEFAULT 30,
  WeeklyOffs VARCHAR(100) NOT NULL DEFAULT 'Sunday'
);
CREATE TABLE IF NOT EXISTS Employees (
  Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  EnrollNo VARCHAR(24) NOT NULL UNIQUE,
  Name VARCHAR(100) NOT NULL,
  Designation VARCHAR(100) NULL,
  Phone VARCHAR(20) NULL,
  JoinDate TIMESTAMP NULL,
  BadgeNo VARCHAR(30) NULL,
  Gender VARCHAR(10) NULL,
  Nationality VARCHAR(50) NULL,
  OfficeTel VARCHAR(20) NULL,
  HomeAddress VARCHAR(250) NULL,
  Email VARCHAR(100) NULL,
  BirthDate TIMESTAMP NULL,
  PhotoBase64 TEXT NULL,
  DepartmentId INT NULL REFERENCES Departments (Id) ON DELETE SET NULL,
  ShiftId INT NULL REFERENCES Shifts (Id) ON DELETE SET NULL,
  Privilege INT NOT NULL DEFAULT 0,
  DevicePassword VARCHAR(20) NULL,
  CardNo VARCHAR(20) NULL,
  MonthlySalary NUMERIC(18,2) NOT NULL DEFAULT 0,
  OtRatePerHour NUMERIC(18,2) NOT NULL DEFAULT 0,
  IsActive BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE IF NOT EXISTS FingerTemplates (
  Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  EmployeeId INT NOT NULL REFERENCES Employees (Id) ON DELETE CASCADE,
  FingerIndex INT NOT NULL,
  Flag INT NOT NULL DEFAULT 1,
  Template TEXT NOT NULL,
  UNIQUE (EmployeeId, FingerIndex)
);
CREATE TABLE IF NOT EXISTS AttendanceLogs (
  Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  EnrollNo VARCHAR(24) NOT NULL,
  PunchTime TIMESTAMP NOT NULL,
  VerifyMode INT NOT NULL,
  InOutMode INT NOT NULL,
  WorkCode INT NOT NULL,
  Source INT NOT NULL,
  Remark VARCHAR(200) NULL,
  UNIQUE (EnrollNo, PunchTime)
);
CREATE INDEX IF NOT EXISTS IX_AttendanceLogs_PunchTime ON AttendanceLogs (PunchTime);
CREATE TABLE IF NOT EXISTS LeaveTypes (
  Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Name VARCHAR(50) NOT NULL,
  Code VARCHAR(10) NOT NULL,
  IsPaid BOOLEAN NOT NULL DEFAULT TRUE,
  YearlyQuota DOUBLE PRECISION NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS LeaveEntries (
  Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  EmployeeId INT NOT NULL REFERENCES Employees (Id) ON DELETE CASCADE,
  LeaveTypeId INT NOT NULL REFERENCES LeaveTypes (Id) ON DELETE RESTRICT,
  FromDate TIMESTAMP NOT NULL,
  ToDate TIMESTAMP NOT NULL,
  IsHalfDay BOOLEAN NOT NULL DEFAULT FALSE,
  Reason VARCHAR(200) NULL,
  Status INT NOT NULL DEFAULT 0,
  AppliedOn TIMESTAMP NULL,
  ApprovedBy VARCHAR(100) NULL,
  ApprovedOn TIMESTAMP NULL
);
CREATE TABLE IF NOT EXISTS Holidays (
  Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Date TIMESTAMP NOT NULL UNIQUE,
  Name VARCHAR(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS DeviceProfiles (
  Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Name VARCHAR(100) NOT NULL DEFAULT 'LX50',
  Kind INT NOT NULL DEFAULT 0,
  MachineNumber INT NOT NULL DEFAULT 1,
  ComPort VARCHAR(10) NOT NULL DEFAULT 'COM3',
  BaudRate INT NOT NULL DEFAULT 115200,
  IpAddress VARCHAR(50) NOT NULL DEFAULT '192.168.1.201',
  TcpPort INT NOT NULL DEFAULT 4370,
  CommPassword INT NOT NULL DEFAULT 0,
  LastDownload TIMESTAMP NULL,
  ProductName VARCHAR(50) NULL,
  SerialNumber VARCHAR(50) NULL,
  Firmware VARCHAR(50) NULL,
  UserCount INT NULL,
  AdminCount INT NULL,
  FpCount INT NULL,
  FaceCount INT NULL,
  PasswordCount INT NULL,
  LogCount INT NULL
);
CREATE TABLE IF NOT EXISTS AppSettings (
  Key VARCHAR(50) NOT NULL PRIMARY KEY,
  Value VARCHAR(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS PiCommands (
  Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  DeviceSerial VARCHAR(50) NOT NULL,
  Type VARCHAR(30) NOT NULL,
  Body TEXT NOT NULL,
  Status VARCHAR(20) NOT NULL DEFAULT 'pending',
  Error VARCHAR(500) NULL,
  Result TEXT NULL,
  CreatedAt TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
  FinishedAt TIMESTAMP NULL,
  CreatedBy VARCHAR(100) NULL
);
CREATE TABLE IF NOT EXISTS PiDeviceUsers (
  DeviceSerial VARCHAR(50) NOT NULL,
  UserId VARCHAR(24) NOT NULL,
  Name VARCHAR(100) NOT NULL,
  Privilege INT NOT NULL,
  Card BIGINT NOT NULL,
  UpdatedAt TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
  PRIMARY KEY (DeviceSerial, UserId)
);
CREATE TABLE IF NOT EXISTS PortalAccounts (
  EmployeeId INT NOT NULL PRIMARY KEY,
  PasswordHash VARCHAR(200) NOT NULL,
  IsManager BOOLEAN NOT NULL DEFAULT FALSE,
  MustChange BOOLEAN NOT NULL DEFAULT TRUE,
  LastLogin TIMESTAMP NULL,
  CreatedAt TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP
);
CREATE TABLE IF NOT EXISTS EmployeeRequests (
  Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  EmployeeId INT NOT NULL,
  Type VARCHAR(20) NOT NULL,             -- Regularisation | Expense | Advance | Overtime | CompOff | Profile
  RequestDate DATE NOT NULL,             -- day of the missed punch / of the expense / of the request
  PunchTime TIMESTAMP NULL,              -- Regularisation: the punch to add when approved
  Category VARCHAR(50) NULL,             -- Expense: Travel, Food ...; Regularisation: Check-In / Check-Out
  Amount NUMERIC(18,2) NULL,
  Installments INT NULL,                 -- Advance: months to recover it in
  Details VARCHAR(500) NULL,
  Attachment TEXT NULL,                  -- receipt photo (base64 JPEG)
  Status INT NOT NULL DEFAULT 0,         -- 0 pending, 1 approved, 2 rejected (as LeaveEntries)
  DecidedBy VARCHAR(100) NULL,
  DecidedOn TIMESTAMP NULL,
  DecisionNote VARCHAR(200) NULL,
  CreatedAt TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
  Payload TEXT NULL                      -- Profile: JSON of the changes
);
CREATE TABLE IF NOT EXISTS EmployeeProfiles (
  EmployeeId INT NOT NULL PRIMARY KEY,
  ReportingManagerId INT NULL,
  EmergencyName VARCHAR(100) NULL,
  EmergencyRelation VARCHAR(50) NULL,
  EmergencyPhone VARCHAR(20) NULL,
  BloodGroup VARCHAR(5) NULL,
  MaritalStatus VARCHAR(20) NULL,
  PersonalEmail VARCHAR(100) NULL,
  Pan VARCHAR(10) NULL,
  Aadhaar VARCHAR(12) NULL,
  Uan VARCHAR(12) NULL,
  PfNo VARCHAR(30) NULL,
  EsiNo VARCHAR(20) NULL,
  BankName VARCHAR(100) NULL,
  BankAccount VARCHAR(30) NULL,
  BankIfsc VARCHAR(11) NULL,
  AccountHolder VARCHAR(100) NULL,
  PfApplicable BOOLEAN NOT NULL DEFAULT FALSE,
  EsiApplicable BOOLEAN NOT NULL DEFAULT FALSE,
  PtApplicable BOOLEAN NOT NULL DEFAULT FALSE,
  TdsMonthly NUMERIC(18,2) NOT NULL DEFAULT 0,
  UpdatedAt TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP
);
CREATE TABLE IF NOT EXISTS EmployeeDocuments (
  Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  EmployeeId INT NOT NULL,
  Title VARCHAR(100) NOT NULL,
  FileName VARCHAR(200) NOT NULL,
  ContentType VARCHAR(100) NOT NULL,
  SizeBytes INT NOT NULL,
  Data TEXT NOT NULL,                    -- base64
  UploadedBy VARCHAR(100) NULL,
  UploadedAt TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP
);
CREATE TABLE IF NOT EXISTS ShiftExtras (
  ShiftId INT NOT NULL PRIMARY KEY,
  BreakStart TIME NULL,
  BreakEnd TIME NULL,
  BreakMinutes INT NOT NULL DEFAULT 0,   -- allowed break; 0 = no break rule
  DeductBreak BOOLEAN NOT NULL DEFAULT TRUE -- the break is not working time
);
CREATE TABLE IF NOT EXISTS ShiftRoster (
  EmployeeId INT NOT NULL,
  Date DATE NOT NULL,
  ShiftId INT NULL,                      -- NULL with IsOff: day off
  IsOff BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (EmployeeId, Date)
);
CREATE TABLE IF NOT EXISTS SalaryComponents (
  Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Name VARCHAR(60) NOT NULL,
  Kind VARCHAR(10) NOT NULL,             -- Earning | Deduction
  Calc VARCHAR(10) NOT NULL,             -- PctGross | PctBasic | Fixed | Balance
  Value NUMERIC(18,2) NOT NULL DEFAULT 0,
  IsBasic BOOLEAN NOT NULL DEFAULT FALSE, -- the Basic (PF wages, % of basic)
  SortOrder INT NOT NULL DEFAULT 0,
  IsActive BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE IF NOT EXISTS EmployeeSalaryComponents (
  EmployeeId INT NOT NULL,
  ComponentId INT NOT NULL,
  Amount NUMERIC(18,2) NOT NULL,         -- monthly amount instead of the component's own rule
  PRIMARY KEY (EmployeeId, ComponentId)
);
CREATE TABLE IF NOT EXISTS Notifications (
  Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  EmployeeId INT NULL,                   -- NULL = for the administrator program (HR)
  Title VARCHAR(150) NOT NULL,
  Body VARCHAR(500) NULL,
  Link VARCHAR(100) NULL,
  IsRead BOOLEAN NOT NULL DEFAULT FALSE,
  CreatedAt TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP
);
CREATE TABLE IF NOT EXISTS AuditLog (
  Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  At TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
  UserName VARCHAR(100) NOT NULL,
  Role VARCHAR(20) NULL,
  Action VARCHAR(100) NOT NULL,
  Path VARCHAR(200) NOT NULL,
  Details VARCHAR(1000) NULL,
  Ip VARCHAR(50) NULL
);
CREATE INDEX IF NOT EXISTS IX_AuditLog_At ON AuditLog (At);
CREATE TABLE IF NOT EXISTS AdminUsers (
  Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  UserName VARCHAR(50) NOT NULL UNIQUE,
  FullName VARCHAR(100) NULL,
  PasswordHash VARCHAR(200) NOT NULL,
  Role VARCHAR(20) NOT NULL,             -- Admin | HR | Payroll | Viewer
  IsActive BOOLEAN NOT NULL DEFAULT TRUE,
  LastLogin TIMESTAMP NULL,
  CreatedAt TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP
);
CREATE TABLE IF NOT EXISTS WebBlobs (
  Key VARCHAR(50) NOT NULL PRIMARY KEY,
  Value TEXT NOT NULL
)`;

/** Seed rows, each only when its table (or row) is still missing. */
const SEED = `
INSERT INTO Shifts (Name) SELECT 'General' WHERE NOT EXISTS (SELECT 1 FROM Shifts);
INSERT INTO Departments (Name) SELECT 'General' WHERE NOT EXISTS (SELECT 1 FROM Departments);
INSERT INTO LeaveTypes (Code, Name, IsPaid) SELECT * FROM (VALUES ('CL', 'Casual Leave', TRUE), ('SL', 'Sick Leave', TRUE),
  ('EL', 'Earned Leave', TRUE), ('LWP', 'Leave Without Pay', FALSE)) v WHERE NOT EXISTS (SELECT 1 FROM LeaveTypes);
INSERT INTO DeviceProfiles (Name) SELECT 'LX50' WHERE NOT EXISTS (SELECT 1 FROM DeviceProfiles);
INSERT INTO SalaryComponents (Name, Kind, Calc, Value, IsBasic, SortOrder) SELECT * FROM (VALUES
  ('Basic', 'Earning', 'PctGross', 50, TRUE, 1), ('HRA', 'Earning', 'PctBasic', 40, FALSE, 2),
  ('Special Allowance', 'Earning', 'Balance', 0, FALSE, 9)) v WHERE NOT EXISTS (SELECT 1 FROM SalaryComponents);
INSERT INTO LeaveTypes (Name, Code, IsPaid, YearlyQuota)
  SELECT 'Compensatory Off', 'CO', TRUE, 0 WHERE NOT EXISTS (SELECT 1 FROM LeaveTypes WHERE Code = 'CO')`;

/** Every table of the web version, in the order they can be filled (used by the data copy and the backup). */
export const TABLES = [...SCHEMA.matchAll(/CREATE TABLE IF NOT EXISTS (\w+)/g)].map((m) => m[1]);

// Column spelling for results of SELECT * (see config/db).
registerColumns(SCHEMA.match(/^\s+([A-Z]\w*)\s+[A-Z]/gm)!.map((l) => l.trim().split(/\s+/)[0]));
registerColumns(TABLES);

export async function ensureWebTables() {
  await exec(SCHEMA);
  await exec(SEED);
}
