import { exec, registerColumns } from '../db';

/**
 * Tables of the inventory service (its own database). Inv* are the inventory's own data. Dir* are a read-only copy of
 * attendance's employees, departments and work sites, fetched over attendance's API (attendance.ts): documents keep the
 * EmployeeId / DepartmentId / SiteId and the name as it was, so deleting an employee in attendance never breaks history.
 *
 * Stock: InvStock is the balance per item and store (quantity and weighted average cost); every change is a row of
 * InvMovements (the ledger). Documents: purchase orders → goods receipts, requisitions → issues (→ returns),
 * transfers / adjustments / stock counts (InvStockDocs). InvAlerts are the store's alerts (low stock, late POs, overdue
 * returns ...), InvCounters the document numbers, InvSettings the module's settings.
 */
const SCHEMA = `
CREATE TABLE IF NOT EXISTS DirEmployees (
  Id INT NOT NULL PRIMARY KEY,
  EnrollNo VARCHAR(50) NOT NULL,
  Name VARCHAR(200) NOT NULL,
  DepartmentId INT NULL,
  Designation VARCHAR(200) NULL,
  IsActive BOOLEAN NOT NULL DEFAULT TRUE,
  CardNo VARCHAR(100) NULL
);
CREATE TABLE IF NOT EXISTS DirDepartments (
  Id INT NOT NULL PRIMARY KEY,
  Name VARCHAR(200) NOT NULL,
  ParentId INT NULL
);
CREATE TABLE IF NOT EXISTS DirSites (
  Id INT NOT NULL PRIMARY KEY,
  Name VARCHAR(200) NOT NULL,
  AllEmployees BOOLEAN NOT NULL DEFAULT TRUE,
  IsActive BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE IF NOT EXISTS DirSiteEmployees (
  SiteId INT NOT NULL,
  EmployeeId INT NOT NULL,
  PRIMARY KEY (SiteId, EmployeeId)
);
CREATE TABLE IF NOT EXISTS InvSettings (
  Key VARCHAR(50) NOT NULL PRIMARY KEY,
  Value VARCHAR(500) NOT NULL
);
CREATE TABLE IF NOT EXISTS InvCounters (
  Key VARCHAR(30) NOT NULL PRIMARY KEY,
  Value INT NOT NULL
);
CREATE TABLE IF NOT EXISTS InvCategories (
  Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Name VARCHAR(100) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS InvWarehouses (
  Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Name VARCHAR(100) NOT NULL UNIQUE,
  Address VARCHAR(300) NULL,
  InchargeId INT NULL,
  IsActive BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE IF NOT EXISTS InvSuppliers (
  Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Name VARCHAR(150) NOT NULL,
  ContactPerson VARCHAR(100) NULL,
  Phone VARCHAR(30) NULL,
  Email VARCHAR(100) NULL,
  Gstin VARCHAR(15) NULL,
  Address VARCHAR(300) NULL,
  LeadTimeDays INT NOT NULL DEFAULT 7,   -- expected delivery of a PO = order date + this
  IsActive BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE IF NOT EXISTS InvItems (
  Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Code VARCHAR(30) NOT NULL UNIQUE,
  Name VARCHAR(150) NOT NULL,
  CategoryId INT NULL REFERENCES InvCategories (Id) ON DELETE SET NULL,
  Unit VARCHAR(20) NOT NULL DEFAULT 'Nos',
  Hsn VARCHAR(10) NULL,
  GstRate NUMERIC(5,2) NOT NULL DEFAULT 18,
  PurchasePrice NUMERIC(18,2) NOT NULL DEFAULT 0, -- last / expected price (new POs use it)
  ReorderLevel NUMERIC(18,3) NOT NULL DEFAULT 0,  -- below this (stock + on order) the item is re-ordered; 0 = never
  ReorderQty NUMERIC(18,3) NOT NULL DEFAULT 0,    -- quantity of an automatic PO; 0 = up to twice the level
  PreferredSupplierId INT NULL REFERENCES InvSuppliers (Id) ON DELETE SET NULL,
  IsReturnable BOOLEAN NOT NULL DEFAULT FALSE,    -- tools, laptops, uniforms: issued, then given back
  ReturnDays INT NOT NULL DEFAULT 0,              -- returnable: due back after this many days; 0 = no due date
  Description VARCHAR(500) NULL,
  IsActive BOOLEAN NOT NULL DEFAULT TRUE,
  CreatedAt TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP
);
CREATE TABLE IF NOT EXISTS InvStock (
  ItemId INT NOT NULL REFERENCES InvItems (Id) ON DELETE CASCADE,
  WarehouseId INT NOT NULL REFERENCES InvWarehouses (Id) ON DELETE CASCADE,
  Qty NUMERIC(18,3) NOT NULL DEFAULT 0,
  AvgCost NUMERIC(18,4) NOT NULL DEFAULT 0,
  PRIMARY KEY (ItemId, WarehouseId)
);
CREATE TABLE IF NOT EXISTS InvMovements (
  Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  At TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
  ItemId INT NOT NULL REFERENCES InvItems (Id) ON DELETE CASCADE,
  WarehouseId INT NOT NULL REFERENCES InvWarehouses (Id) ON DELETE CASCADE,
  Type VARCHAR(20) NOT NULL,             -- Opening | Receipt | Issue | Return | TransferOut | TransferIn | Adjustment
  Qty NUMERIC(18,3) NOT NULL,            -- + in, - out
  UnitCost NUMERIC(18,4) NOT NULL DEFAULT 0,
  BalanceAfter NUMERIC(18,3) NOT NULL,   -- stock of the item in this store after the movement
  RefType VARCHAR(20) NULL,              -- Receipt | Issue | StockDoc | Item
  RefId INT NULL,
  RefNo VARCHAR(30) NULL,
  EmployeeId INT NULL,
  DepartmentId INT NULL,
  Note VARCHAR(300) NULL,
  CreatedBy VARCHAR(100) NULL
);
CREATE INDEX IF NOT EXISTS IX_InvMovements_At ON InvMovements (At);
CREATE INDEX IF NOT EXISTS IX_InvMovements_Item ON InvMovements (ItemId, At);
CREATE TABLE IF NOT EXISTS InvPurchaseOrders (
  Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  PoNo VARCHAR(30) NOT NULL UNIQUE,
  SupplierId INT NOT NULL REFERENCES InvSuppliers (Id) ON DELETE RESTRICT,
  WarehouseId INT NOT NULL REFERENCES InvWarehouses (Id) ON DELETE RESTRICT,
  OrderDate DATE NOT NULL DEFAULT CURRENT_DATE,
  ExpectedDate DATE NULL,
  Status VARCHAR(12) NOT NULL DEFAULT 'Draft', -- Draft | Ordered | Partial | Received | Closed | Cancelled
  IsAuto BOOLEAN NOT NULL DEFAULT FALSE,       -- made by the automatic re-order
  Notes VARCHAR(500) NULL,
  CreatedBy VARCHAR(100) NULL,
  CreatedAt TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP
);
CREATE TABLE IF NOT EXISTS InvPurchaseOrderLines (
  Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  PoId INT NOT NULL REFERENCES InvPurchaseOrders (Id) ON DELETE CASCADE,
  ItemId INT NOT NULL REFERENCES InvItems (Id) ON DELETE RESTRICT,
  Qty NUMERIC(18,3) NOT NULL,
  ReceivedQty NUMERIC(18,3) NOT NULL DEFAULT 0,
  UnitPrice NUMERIC(18,2) NOT NULL DEFAULT 0,
  GstRate NUMERIC(5,2) NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS InvReceipts (
  Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  GrnNo VARCHAR(30) NOT NULL UNIQUE,
  PoId INT NULL REFERENCES InvPurchaseOrders (Id) ON DELETE SET NULL,
  SupplierId INT NULL REFERENCES InvSuppliers (Id) ON DELETE SET NULL,
  WarehouseId INT NOT NULL REFERENCES InvWarehouses (Id) ON DELETE RESTRICT,
  ReceivedOn DATE NOT NULL DEFAULT CURRENT_DATE,
  InvoiceNo VARCHAR(50) NULL,
  Note VARCHAR(300) NULL,
  CreatedBy VARCHAR(100) NULL,
  CreatedAt TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP
);
CREATE TABLE IF NOT EXISTS InvReceiptLines (
  Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ReceiptId INT NOT NULL REFERENCES InvReceipts (Id) ON DELETE CASCADE,
  PoLineId INT NULL REFERENCES InvPurchaseOrderLines (Id) ON DELETE SET NULL,
  ItemId INT NOT NULL REFERENCES InvItems (Id) ON DELETE RESTRICT,
  Qty NUMERIC(18,3) NOT NULL,
  UnitPrice NUMERIC(18,2) NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS InvRequisitions (
  Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ReqNo VARCHAR(30) NOT NULL UNIQUE,
  EmployeeId INT NULL,
  EmployeeName VARCHAR(100) NULL,        -- as it was when requested
  DepartmentId INT NULL,
  WarehouseId INT NOT NULL REFERENCES InvWarehouses (Id) ON DELETE RESTRICT,
  Purpose VARCHAR(300) NULL,
  Status VARCHAR(12) NOT NULL DEFAULT 'Pending', -- Pending | Approved | PartIssued | Issued | Rejected | Cancelled
  Source VARCHAR(10) NOT NULL DEFAULT 'admin',   -- portal (the employee) | admin (the store, on behalf)
  RequestedBy VARCHAR(100) NULL,
  CreatedAt TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
  DecidedBy VARCHAR(100) NULL,
  DecidedOn TIMESTAMP NULL,
  DecisionNote VARCHAR(300) NULL
);
CREATE TABLE IF NOT EXISTS InvRequisitionLines (
  Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  RequisitionId INT NOT NULL REFERENCES InvRequisitions (Id) ON DELETE CASCADE,
  ItemId INT NOT NULL REFERENCES InvItems (Id) ON DELETE RESTRICT,
  Qty NUMERIC(18,3) NOT NULL,
  IssuedQty NUMERIC(18,3) NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS InvIssues (
  Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  IssueNo VARCHAR(30) NOT NULL UNIQUE,
  RequisitionId INT NULL REFERENCES InvRequisitions (Id) ON DELETE SET NULL,
  EmployeeId INT NULL,
  EmployeeName VARCHAR(100) NULL,
  DepartmentId INT NULL,
  WarehouseId INT NOT NULL REFERENCES InvWarehouses (Id) ON DELETE RESTRICT,
  IssuedOn TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
  IssuedBy VARCHAR(100) NULL,
  Note VARCHAR(300) NULL
);
CREATE TABLE IF NOT EXISTS InvIssueLines (
  Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  IssueId INT NOT NULL REFERENCES InvIssues (Id) ON DELETE CASCADE,
  ItemId INT NOT NULL REFERENCES InvItems (Id) ON DELETE RESTRICT,
  Qty NUMERIC(18,3) NOT NULL,
  UnitCost NUMERIC(18,4) NOT NULL DEFAULT 0,
  ReturnedQty NUMERIC(18,3) NOT NULL DEFAULT 0,
  DueDate DATE NULL,                     -- returnable items: to be given back by
  RemindedOn DATE NULL                   -- last overdue reminder to the employee
);
CREATE TABLE IF NOT EXISTS InvStockDocs (
  Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  DocNo VARCHAR(30) NOT NULL UNIQUE,
  Kind VARCHAR(12) NOT NULL,             -- Transfer | Adjustment | Count
  WarehouseId INT NOT NULL REFERENCES InvWarehouses (Id) ON DELETE RESTRICT,
  ToWarehouseId INT NULL REFERENCES InvWarehouses (Id) ON DELETE RESTRICT,
  Reason VARCHAR(300) NULL,
  CreatedBy VARCHAR(100) NULL,
  CreatedAt TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP
);
CREATE TABLE IF NOT EXISTS InvAlerts (
  Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Kind VARCHAR(20) NOT NULL,             -- LowStock | AutoPO | LatePO | Overdue | ExitClearance | PendingReq | CanIssue
  AlertKey VARCHAR(60) NOT NULL,         -- one open alert per key (e.g. low:12)
  Title VARCHAR(150) NOT NULL,
  Body VARCHAR(500) NULL,
  Link VARCHAR(100) NULL,
  IsRead BOOLEAN NOT NULL DEFAULT FALSE,
  IsResolved BOOLEAN NOT NULL DEFAULT FALSE,
  CreatedAt TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS UX_InvAlerts_Open ON InvAlerts (AlertKey) WHERE NOT IsResolved;
-- Material for work sites (2026-10-08): the site is one of attendance's DirSites. A requisition / issue can be for a
-- site; what is issued for a site stays "at the site" until it is installed there (InvSiteUsage, InvIssueLines.ConsumedQty)
-- or given back. SiteName is kept as it was, so deleting a site in attendance never fails and history stays readable.
ALTER TABLE InvRequisitions ADD COLUMN IF NOT EXISTS SiteId INT NULL;
ALTER TABLE InvRequisitions ADD COLUMN IF NOT EXISTS SiteName VARCHAR(100) NULL;
ALTER TABLE InvIssues ADD COLUMN IF NOT EXISTS SiteId INT NULL;
ALTER TABLE InvIssues ADD COLUMN IF NOT EXISTS SiteName VARCHAR(100) NULL;
ALTER TABLE InvIssueLines ADD COLUMN IF NOT EXISTS ConsumedQty NUMERIC(18,3) NOT NULL DEFAULT 0;
CREATE INDEX IF NOT EXISTS IX_InvIssues_Site ON InvIssues (SiteId) WHERE SiteId IS NOT NULL;
CREATE TABLE IF NOT EXISTS InvSiteUsage (
  Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  IssueLineId INT NOT NULL REFERENCES InvIssueLines (Id) ON DELETE CASCADE,
  IssueId INT NOT NULL REFERENCES InvIssues (Id) ON DELETE CASCADE,
  SiteId INT NULL,
  SiteName VARCHAR(100) NULL,
  ItemId INT NOT NULL REFERENCES InvItems (Id) ON DELETE RESTRICT,
  Qty NUMERIC(18,3) NOT NULL,
  UnitCost NUMERIC(18,4) NOT NULL DEFAULT 0,
  UsedOn DATE NOT NULL DEFAULT CURRENT_DATE,
  Note VARCHAR(300) NULL,
  RecordedBy VARCHAR(100) NULL,           -- store user, or "<AC No> <name>" from the portal / app
  CreatedAt TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP
);
-- Serial / tagged items and employee bins (2026-10-08). An item is tracked by quantity (consumables, returnables) or by
-- serial: every unit (boom barrier, turnstile, laptop) is an InvUnits row with its serial number and RFID / QR tag.
-- For a serial item the units in a store always match InvStock (stock.service post() creates / moves them), so issue,
-- return, transfer, count and installed-at-site know exactly which unit went where. InvUnitEvents is each unit's history.
-- Barcode: the QR / barcode printed on an item's pack (scanning it picks the item). InvBins: an employee's bin limit
-- (NULL = the BinLimit setting); every employee has a bin, a row is only needed for an own limit or note.
ALTER TABLE InvItems ADD COLUMN IF NOT EXISTS TrackBy VARCHAR(10) NOT NULL DEFAULT 'Qty';
ALTER TABLE InvItems ADD COLUMN IF NOT EXISTS Barcode VARCHAR(100) NULL;
CREATE UNIQUE INDEX IF NOT EXISTS UX_InvItems_Barcode ON InvItems (lower(Barcode)) WHERE Barcode IS NOT NULL;
CREATE TABLE IF NOT EXISTS InvUnits (
  Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ItemId INT NOT NULL REFERENCES InvItems (Id) ON DELETE CASCADE,
  SerialNo VARCHAR(60) NOT NULL,
  Tag VARCHAR(100) NULL,                  -- RFID / QR code stuck on the unit
  Status VARCHAR(12) NOT NULL DEFAULT 'InStore', -- InStore | Transit | Issued | Installed | Damaged | Lost | Scrapped
  WarehouseId INT NULL REFERENCES InvWarehouses (Id) ON DELETE SET NULL,  -- InStore: the store
  IssueLineId INT NULL REFERENCES InvIssueLines (Id) ON DELETE SET NULL, -- Issued / Installed: the issue line
  EmployeeId INT NULL,      -- Issued: who holds it
  SiteId INT NULL,          -- Issued for / installed at
  SiteName VARCHAR(100) NULL,
  Cost NUMERIC(18,4) NOT NULL DEFAULT 0,
  Note VARCHAR(300) NULL,
  CreatedAt TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
  UpdatedAt TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS UX_InvUnits_Serial ON InvUnits (ItemId, lower(SerialNo));
CREATE UNIQUE INDEX IF NOT EXISTS UX_InvUnits_Tag ON InvUnits (lower(Tag)) WHERE Tag IS NOT NULL;
CREATE INDEX IF NOT EXISTS IX_InvUnits_Store ON InvUnits (ItemId, WarehouseId) WHERE Status = 'InStore';
CREATE TABLE IF NOT EXISTS InvIssueUnits (
  IssueLineId INT NOT NULL REFERENCES InvIssueLines (Id) ON DELETE CASCADE,
  UnitId INT NOT NULL REFERENCES InvUnits (Id) ON DELETE CASCADE,
  Status VARCHAR(12) NOT NULL DEFAULT 'Out', -- Out | Returned | Installed | Damaged | Lost
  ClosedAt TIMESTAMP NULL,
  PRIMARY KEY (IssueLineId, UnitId)
);
CREATE TABLE IF NOT EXISTS InvUnitEvents (
  Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  UnitId INT NOT NULL REFERENCES InvUnits (Id) ON DELETE CASCADE,
  At TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
  Event VARCHAR(20) NOT NULL,            -- Received | Opening | Registered | Issued | Returned | Installed | Damaged | Lost | Scrapped | Transferred | Tagged | Edited
  RefNo VARCHAR(30) NULL,
  WarehouseId INT NULL,
  EmployeeId INT NULL,
  EmployeeName VARCHAR(100) NULL,
  SiteName VARCHAR(100) NULL,
  Note VARCHAR(300) NULL,
  CreatedBy VARCHAR(100) NULL
);
CREATE INDEX IF NOT EXISTS IX_InvUnitEvents_Unit ON InvUnitEvents (UnitId, At);
CREATE TABLE IF NOT EXISTS InvBins (
  EmployeeId INT NOT NULL PRIMARY KEY,
  MaxItems INT NULL,                     -- own limit; NULL = the BinLimit setting; 0 = no limit
  Note VARCHAR(300) NULL,
  UpdatedBy VARCHAR(100) NULL,
  UpdatedAt TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP
);
-- Locations inside a store (2026-10-09): rack / row / column, each with a QR label (LOC-<Id>) or an RFID tag. Stock is
-- always on a location: InvLocStock per item and location adds up to InvStock of the store, serial units in a store have
-- their LocationId, every movement says its location. Every store has one system location RECEIVING (the inward
-- counter): goods booked in without a location land there and are put away onto the racks (Move).
CREATE TABLE IF NOT EXISTS InvLocations (
  Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  WarehouseId INT NOT NULL REFERENCES InvWarehouses (Id) ON DELETE CASCADE,
  Code VARCHAR(40) NOT NULL,              -- R03-2-4 (rack-row-column) or RECEIVING
  Rack VARCHAR(20) NOT NULL,
  RowNo VARCHAR(10) NOT NULL DEFAULT '',
  ColNo VARCHAR(10) NOT NULL DEFAULT '',
  Tag VARCHAR(100) NULL,                  -- RFID tag on the rack position (the QR label is LOC-<Id>)
  IsSystem BOOLEAN NOT NULL DEFAULT FALSE, -- RECEIVING
  IsActive BOOLEAN NOT NULL DEFAULT TRUE,
  Note VARCHAR(200) NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS UX_InvLocations_Code ON InvLocations (WarehouseId, lower(Code));
CREATE UNIQUE INDEX IF NOT EXISTS UX_InvLocations_Tag ON InvLocations (lower(Tag)) WHERE Tag IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS UX_InvLocations_Receiving ON InvLocations (WarehouseId) WHERE IsSystem;
CREATE TABLE IF NOT EXISTS InvLocStock (
  ItemId INT NOT NULL REFERENCES InvItems (Id) ON DELETE CASCADE,
  LocationId INT NOT NULL REFERENCES InvLocations (Id) ON DELETE CASCADE,
  Qty NUMERIC(18,3) NOT NULL DEFAULT 0,
  PRIMARY KEY (ItemId, LocationId)
);
ALTER TABLE InvMovements ADD COLUMN IF NOT EXISTS LocationId INT NULL REFERENCES InvLocations (Id) ON DELETE SET NULL;
ALTER TABLE InvUnits ADD COLUMN IF NOT EXISTS LocationId INT NULL REFERENCES InvLocations (Id) ON DELETE SET NULL;
ALTER TABLE InvUnitEvents ADD COLUMN IF NOT EXISTS LocationId INT NULL`;

/**
 * Keeps "stock is always on a location" true for data from before locations (and after a restore): every store gets its
 * RECEIVING location, stock not on any location goes there, units in a store without a location too.
 */
const LOCATION_FIX = `
INSERT INTO InvLocations (WarehouseId, Code, Rack, IsSystem)
  SELECT w.Id, 'RECEIVING', 'RECEIVING', TRUE FROM InvWarehouses w
  WHERE NOT EXISTS (SELECT 1 FROM InvLocations l WHERE l.WarehouseId = w.Id AND l.IsSystem);
INSERT INTO InvLocStock (ItemId, LocationId, Qty)
  SELECT s.ItemId, r.Id, s.Qty - COALESCE((SELECT SUM(x.Qty) FROM InvLocStock x JOIN InvLocations y ON y.Id = x.LocationId
    WHERE x.ItemId = s.ItemId AND y.WarehouseId = s.WarehouseId), 0)
  FROM InvStock s JOIN InvLocations r ON r.WarehouseId = s.WarehouseId AND r.IsSystem
  WHERE s.Qty <> COALESCE((SELECT SUM(x.Qty) FROM InvLocStock x JOIN InvLocations y ON y.Id = x.LocationId
    WHERE x.ItemId = s.ItemId AND y.WarehouseId = s.WarehouseId), 0)
  ON CONFLICT (ItemId, LocationId) DO UPDATE SET Qty = InvLocStock.Qty + EXCLUDED.Qty;
UPDATE InvUnits u SET LocationId = r.Id FROM InvLocations r
  WHERE u.Status = 'InStore' AND u.LocationId IS NULL AND r.WarehouseId = u.WarehouseId AND r.IsSystem`;

const SEED = `
INSERT INTO InvWarehouses (Name) SELECT 'Main Store' WHERE NOT EXISTS (SELECT 1 FROM InvWarehouses);
INSERT INTO InvCategories (Name) SELECT * FROM (VALUES ('Consumables'), ('Stationery'), ('Tools & Equipment'), ('IT Assets'),
  ('Safety / PPE'), ('Spares')) v WHERE NOT EXISTS (SELECT 1 FROM InvCategories)`;

/** In the order they can be filled (backup / restore), after the attendance tables. */
const CREATED = [...SCHEMA.matchAll(/CREATE TABLE IF NOT EXISTS (\w+)/g)].map((m) => m[1]);
/** InvLocations is created late but movements / units refer to it: restore it right after the stores. */
export const INVENTORY_TABLES = CREATED.filter((t) => t.startsWith('Inv') && t !== 'InvLocations').flatMap((t) => (t === 'InvWarehouses' ? [t, 'InvLocations'] : [t]));

registerColumns(SCHEMA.match(/^\s+([A-Z]\w*)\s+[A-Z]/gm)!.map((l) => l.trim().split(/\s+/)[0]));
registerColumns(CREATED);
registerColumns(['SiteId', 'SiteName', 'ConsumedQty', 'TrackBy', 'Barcode']);

export async function ensureInventoryTables() {
  await exec(SCHEMA);
  await exec(SEED);
  await exec(LOCATION_FIX);
}
